[package]
name = "diesel-repository"
version = "0.1.0"
edition = "2021"

[dependencies]
diesel = { version = "2", features = ["postgres_backend"] }
diesel-async = { version = "0", features = ["postgres", "deadpool", "async-connection-wrapper", "sync-connection-wrapper"] }
